//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicationMVC2.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destinos
    {
        public System.Guid id { get; set; }
        public string destino { get; set; }
        public Nullable<System.DateTime> fecha_presentacion { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public System.Guid id_persona { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
